version: "3"
services:
  db: 
    image: "postgres:12-alpine" 
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "5432:5432"
    depends_on:
      - shard1
      - shard2
      - shard3
      - shard4
  shard1: 
    image: "postgres:12-alpine" 
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    volumes:
      - ./init-shard1.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
  shard2: 
    image: "postgres:12-alpine" 
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    volumes:
      - ./init-shard2.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
  shard3: 
    image: "postgres:12-alpine" 
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    volumes:
      - ./init-shard3.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
  shard4: 
    image: "postgres:12-alpine" 
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    volumes:
      - ./init-shard4.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
